import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { QueryObserverResult, UseMutationResult } from '@tanstack/react-query';
import axios from 'axios';
import { request } from 'librechat-data-provider';

export type AutomationRun = { run_id: string | null; run_at: string | null; trigger: string | null; status: string | null; kind: string | null; stage: string | null; generated: boolean | null; error: string | null; duration_ms: number | null; output: string | null; response_message_id: string | null };
export type SecretBindingInput = { id?: string; name?: string; purpose: string; vault: string; item: string; field: string; destination: 'header' | 'env'; key: string };
export type AgentConfigInput = { generate: boolean; profile?: string | null; mcpServers: string[]; mcpTools: string[]; skills: string[] };
export type AutomationPayload = { text?: string; key?: string; value?: string; script?: string; args?: string[]; url?: string; data?: Record<string, unknown>; generate?: boolean };
export type AutomationItem = { id:string; name:string; source:'cron'; target_type:string; payload?:AutomationPayload; agent_config?:AgentConfigInput|null; secret_bindings?:SecretBindingInput[]; schedule:string|null; schedule_raw:string|null; is_recurring:boolean; status:string; ended_reason?:string|null; success_count?:number; retry_count?:number; next_run_at:string|null; last_run_at:string|null; run_count:number; max_runs:number|null; tz:string; conversation_id:string|null; owned_by_user:boolean; in_flight?:boolean; last_runs?:AutomationRun[] };
export type NativeAutomation = { id:string; ownerId:string; state:string; revision:number; config:{versionId:string;title:string;prompt:string;profile:string;schedule:null|{kind:'once';at:string;timezone:string}|{kind:'interval';minutes:number;timezone:string};timeoutMs:number};nextRunAt:string|null;activeRunId:string|null;createdAt:string;updatedAt:string };
export type NativeRun = { id:string;status:string;trigger:string;queuedAt:string;startedAt:string|null;finishedAt:string|null;conversationId:string|null;error:string|null };
export type NativeCapabilities = { supported:boolean;api_enabled:boolean;access?:boolean;worker_ready?:boolean;scheduler_enabled?:boolean;profiles?:string[];schedule_kinds?:string[];commands?:Record<string,boolean>;limits?:Record<string,number> };
export type AutomationsCapabilities={user_scoped:boolean;sources:{cron:{supported:boolean;action_types:Record<string,boolean>;schedule_kinds:string[];commands:Record<string,boolean>;history_depth:number;limits?:Record<string,number>;agent_features?:Record<string,boolean>;secret_features?:{supported:boolean;targets:string[];destinations:string[]}};native:NativeCapabilities}};
export type CreateCronInput={name:string;schedule:string;timezone:string;max_runs?:number|null;target_type:string;conv?:string;payload:AutomationPayload;agent_config?:AgentConfigInput|null;secret_bindings?:SecretBindingInput[]};
export type CreateNativeInput={title:string;prompt:string;profile:string;schedule:null|{kind:'once';at:string;timezone:string}|{kind:'interval';minutes:number;timezone:string};timeoutMs:number};

export type AutomationCatalogs={mcp:{servers:Array<{name:string;title:string;authenticated:boolean;tools:Array<{name:string;description:string;write_or_exec:boolean;available_for_automation:boolean}>}>};skills:Array<{id:string;name:string;title:string;description:string;version:number;always_apply:boolean}>;scripts:string[];native_profiles:string[];secret_bindings:{supported:boolean;provider:string|null;destinations:string[]}};
export const automationsQueryKeys={all:['automations'] as const,list:()=>['automations','cron','list'] as const,byConv:(conv:string)=>['automations','cron','by-conv',conv] as const,capabilities:()=>['automations','capabilities'] as const,catalogs:()=>['automations','catalogs'] as const,detail:(id:string)=>['automations','cron','detail',id] as const,nativeList:()=>['automations','native','list'] as const,nativeDetail:(id:string)=>['automations','native','detail',id] as const,nativeRuns:(id:string)=>['automations','native','runs',id] as const};
const get=<T,>(url:string):Promise<T>=>request.get<T>(url);
const invalidate=(qc:ReturnType<typeof useQueryClient>)=>qc.invalidateQueries(automationsQueryKeys.all);
export function useAutomationsCapabilitiesQuery():QueryObserverResult<AutomationsCapabilities>{return useQuery<AutomationsCapabilities>(automationsQueryKeys.capabilities(),()=>get<AutomationsCapabilities>('/api/automations/cron/capabilities'),{refetchOnWindowFocus:false,staleTime:10000})}
export function useAutomationCatalogsQuery(enabled=true):QueryObserverResult<AutomationCatalogs>{return useQuery(automationsQueryKeys.catalogs(),()=>get<AutomationCatalogs>('/api/automations/cron/catalogs'),{enabled,refetchOnWindowFocus:false,staleTime:30000})}
export type ByConvResponse={items:AutomationItem[];count:number;executor:{healthy:boolean;lag_ms:number|null}};
export function useAutomationsByConvQuery(conversationId?:string|null,refetchInterval=30000):QueryObserverResult<ByConvResponse>{return useQuery<ByConvResponse>(automationsQueryKeys.byConv(conversationId||''),()=>get<ByConvResponse>(`/api/automations/cron/by-conv/${encodeURIComponent(conversationId||'')}`),{enabled:!!conversationId,refetchOnWindowFocus:false,refetchInterval,retry:false})}
export function useCronConvActionMutation(conversationId?:string|null):UseMutationResult<AutomationItem,unknown,{id:string;action:'pause'|'resume'|'cancel'}>{const qc=useQueryClient();return useMutation(({id,action})=>request.post(`/api/automations/cron/by-conv/${encodeURIComponent(conversationId||'')}/actions`,{id,action}),{onSuccess:()=>{qc.invalidateQueries(automationsQueryKeys.all);if(conversationId)qc.invalidateQueries(automationsQueryKeys.byConv(conversationId))}})}
export function useAutomationsListQuery():QueryObserverResult<{items:AutomationItem[];count:number;source:string}>{return useQuery<{items:AutomationItem[];count:number;source:string}>(automationsQueryKeys.list(),()=>get<{items:AutomationItem[];count:number;source:string}>('/api/automations/cron'),{refetchOnWindowFocus:false,staleTime:5000})}
export function useAutomationDetailQuery(id?:string):QueryObserverResult<AutomationItem>{return useQuery<AutomationItem>(automationsQueryKeys.detail(id||''),()=>get<AutomationItem>(`/api/automations/cron/${encodeURIComponent(id||'')}`),{enabled:!!id,refetchOnWindowFocus:false})}
export function useCreateCronMutation():UseMutationResult<AutomationItem,unknown,CreateCronInput>{const qc=useQueryClient();return useMutation((body:CreateCronInput)=>request.post('/api/automations/cron',body),{onSuccess:()=>invalidate(qc)})}
export function useCronActionMutation():UseMutationResult<AutomationItem,unknown,{id:string;action:'pause'|'resume'|'cancel'}>{const qc=useQueryClient();return useMutation(({id,action})=>request.post(`/api/automations/cron/${encodeURIComponent(id)}/actions/${action}`,{}),{onSuccess:()=>invalidate(qc)})}
export function useCronRunNowMutation():UseMutationResult<{result:{status:string;output:string;durationMs:number};jobId:string;duplicate:boolean},unknown,{id:string;key:string}>{const qc=useQueryClient();return useMutation(({id,key})=>axios.post(`/api/automations/cron/${encodeURIComponent(id)}/runs`,{}, {headers:{'Idempotency-Key':key}}).then((r)=>r.data),{onSuccess:()=>invalidate(qc)})}
export function useNativeListQuery(enabled:boolean):QueryObserverResult<{items:NativeAutomation[];nextCursor:string|null}>{return useQuery(automationsQueryKeys.nativeList(),()=>get<{items:NativeAutomation[];nextCursor:string|null}>('/api/schedules?limit=100'),{enabled,refetchOnWindowFocus:false,staleTime:5000,retry:false})}
export function useNativeDetailQuery(id?:string,enabled=true):QueryObserverResult<NativeAutomation>{return useQuery(automationsQueryKeys.nativeDetail(id||''),()=>get<NativeAutomation>(`/api/schedules/${encodeURIComponent(id||'')}`),{enabled:enabled&&!!id,refetchOnWindowFocus:false,retry:false})}
export function useNativeRunsQuery(id?:string,enabled=true):QueryObserverResult<{items:NativeRun[];nextCursor:string|null;capacity:number}>{return useQuery(automationsQueryKeys.nativeRuns(id||''),()=>get<{items:NativeRun[];nextCursor:string|null;capacity:number}>(`/api/schedules/${encodeURIComponent(id||'')}/runs?limit=100`),{enabled:enabled&&!!id,refetchOnWindowFocus:false,retry:false})}
export function useCreateNativeMutation():UseMutationResult<NativeAutomation,unknown,CreateNativeInput>{const qc=useQueryClient();return useMutation((body)=>request.post('/api/schedules',body),{onSuccess:()=>invalidate(qc)})}
export function useUpdateNativeMutation():UseMutationResult<NativeAutomation,unknown,{id:string;body:{revision:number;state?:string;config?:CreateNativeInput}}>{const qc=useQueryClient();return useMutation(({id,body})=>request.put(`/api/schedules/${encodeURIComponent(id)}`,body),{onSuccess:()=>invalidate(qc)})}
export function useNativeRunNowMutation():UseMutationResult<{runId:string;duplicate:boolean},unknown,{id:string;key:string}>{const qc=useQueryClient();return useMutation(({id,key})=>axios.post(`/api/schedules/${encodeURIComponent(id)}/runs`,{}, {headers:{'Idempotency-Key':key}}).then((r)=>r.data),{onSuccess:()=>invalidate(qc)})}
