'use strict';
const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const fsp=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const Module=require('node:module');const express=require('express');const request=require('supertest');
let dir,app,restore;
before(async()=>{dir=await fsp.mkdtemp(path.join(os.tmpdir(),'auto-route-'));process.env.MCP_CRON_DIR=dir;process.env.MCP_CRON_JOBS_FILE=path.join(dir,'jobs.json');process.env.MCP_SESSION_ROOT=path.join(dir,'session');process.env.MCP_CRON_CORE_PATH='/opt/librechat-mcp/mcp/data/git-repos/m894-tech-librechat-mcp-de/mcp/servers/cron-core.mjs';
 const original=Module._load;restore=()=>{Module._load=original};Module._load=function(name,parent,...rest){if(name==='~/server/middleware')return{requireJwtAuth:(req,res,next)=>{const id=req.get('x-user');if(!id)return res.status(401).json({error:'unauthorized'});req.user={id,role:'USER'};next()}};if(name==='@librechat/api')return{isMcpHostUser:(id)=>id==='host',filterMcpServersForUser:(_id,x)=>[...x],isWriteExecTool:()=>false};if(name==='~/server/services/AutomationsCron/owner-cron.cjs')return original.call(this,path.join(__dirname,'owner-cron.cjs'),parent,...rest);if(name==='~/server/services/AutomationsCron/catalogs.cjs')return{buildCatalogs:async()=>({mcp:{servers:[]},skills:[],scripts:[],native_profiles:[],secret_bindings:{supported:false,destinations:[]}})};if(name==='~/server/controllers/mcp')return{getMCPTools:async(_req,res)=>res.status(200).json({servers:{}})};if(name==='~/server/services/Endpoints/agents/skillDeps')return{getSkillDbMethods:()=>({listSkillsByAccess:async()=>({skills:[]})}),withDeploymentSkillIds:(x)=>x};if(name==='~/server/services/PermissionService')return{findAccessibleResources:async()=>[],findPubliclyAccessibleResources:async()=>[]};if(name==='librechat-data-provider')return{ResourceType:{SKILL:'skill'},PermissionBits:{VIEW:1}};return original.call(this,name,parent,...rest)};
 const route=require('../../routes/automationsCron');restore();app=express();app.use('/api/automations/cron',route)});
after(async()=>{restore?.();await fsp.rm(dir,{recursive:true,force:true})});
const api=(method,url,user='alice')=>request(app)[method]('/api/automations/cron'+url).set('x-user',user);
const body={name:'Reminder',schedule:'every 2d',timezone:'Europe/Moscow',target_type:'session_reminder',conv:'11111111-1111-4111-8111-111111111111',payload:{text:'hello'}};
test('requires authentication',async()=>assert.equal((await request(app).get('/api/automations/cron')).status,401));
test('owner creates, lists and foreign user cannot read',async()=>{const c=await api('post','/').send(body);assert.equal(c.status,201,c.text);assert.equal(c.body.owned_by_user,true);const list=await api('get','/');assert.equal(list.body.count,1);assert.equal((await api('get','/'+c.body.id,'bob')).status,404)});
test('pause and resume enforce owner',async()=>{const id=(await api('get','/')).body.items[0].id;assert.equal((await api('post',`/${id}/actions/pause`,'bob')).status,404);assert.equal((await api('post',`/${id}/actions/pause`).send({})).body.status,'paused');assert.equal((await api('post',`/${id}/actions/resume`).send({})).body.status,'active')});
test('manual run uses idempotency and writes owner-scoped session',async()=>{const id=(await api('get','/')).body.items[0].id;const key='route-test-key-123';const first=await api('post',`/${id}/runs`).set('Idempotency-Key',key).send({});assert.equal(first.status,202,first.text);assert.equal(first.body.result.status,'success');const second=await api('post',`/${id}/runs`).set('Idempotency-Key',key).send({});assert.equal(second.status,200);assert.equal(second.body.duplicate,true);const file=path.join(dir,'session','users','alice','11111111-1111-4111-8111-111111111111.json');assert.equal(fs.existsSync(file),true)});
test('resume_conversation accepts every 2d interval',async()=>{
  const r=await api('post','/').send({...body,name:'Resume chat',target_type:'resume_conversation',payload:{text:'continue the thread'}});
  assert.equal(r.status,201,r.text);
  assert.equal(r.body.is_recurring,true);
});
test('host actions are forbidden to normal user',async()=>{const r=await api('post','/').send({...body,target_type:'script',conv:'',payload:{script:'x.sh'}});assert.equal(r.status,403)});
